batch_size: 256
lr: 0.0001
total_iter: 300000
lr_scheduler: 200000
nb_code: 128
code_dim: 512
width: 512
down_t: 2
depth: 3
dilation_growth_rate: 3
loss_vel: 0.5
commit: 0.5
weight_decay: 0.0
mu: 0.99
exp_name: VQVAE_t2m
dataname: t2m
vq_act: relu
quantizer: ema_reset
recons_loss: l1_smooth
gpu_id: 2
